# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsubscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='landingsubscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='landingsubscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
